# Generated by Django 4.2.2 on 2023-11-14 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='users_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
